name: food_delivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  image_path: assets/images/splash/appName.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/splash/
    - assets/images/onBoarding/
    - assets/images/common/
  uses-material-design: true

